### ISSUE TITLE
onos-topo fails to start on microk8s on Ubuntu 18.04

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-topo#26]
I think its that Atomix might not have started properly or something?

I set up microk8s and loaded all the latest docker images in to it and then ran:
```
onit create cluster sean-1 --image-tags="topo=latest,config=latest"
```
It tried starting the cluster, but never finishes with topo
```
scondon@Z420:~/go/src/github.com/onosproject/onos-test$ onit create cluster sean-1 --image-tags="topo=latest,config=latest"
 ✓ Creating cluster namespace
 ✓ Setting up RBAC
 ✓ Setting up Atomix controller 
 ✓ Starting Raft partitions 
 ✓ Adding secrets
⢎⠁ Bootstrapping onos-topo cluster
```

but when I go and get the logs of **onos-topo** I see:
```
scondon@Z420:~/go/src/github.com/onosproject/onos-test$ kubectl logs onos-topo-6b564977f9-62grp -n sean-1
I0816 07:47:39.868782       1 onos-topo.go:69] Starting onos-topo
I0816 07:47:39.869203       1 manager.go:26] Creating Manager
I0816 07:47:39.869217       1 manager.go:37] Starting Manager
F0816 07:47:44.875387       1 onos-topo.go:78] Unable to start onos-topo rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup atomix-controller.sean-1.svc.cluster.local: Try again"
goroutine 1 [running]:
k8s.io/klog.stacks(0xc00013e700, 0xc000216000, 0x12e, 0x222)
	/go/src/github.com/onosproject/onos-topo/vendor/k8s.io/klog/klog.go:855 +0xb1
k8s.io/klog.(*loggingT).output(0x10150a0, 0xc000000003, 0xc000135f10, 0xfbbc08, 0xc, 0x4e, 0x0)
	/go/src/github.com/onosproject/onos-topo/vendor/k8s.io/klog/klog.go:806 +0x2d9
k8s.io/klog.(*loggingT).printDepth(0x10150a0, 0x3, 0x1, 0xc0000eff68, 0x2, 0x2)
	/go/src/github.com/onosproject/onos-topo/vendor/k8s.io/klog/klog.go:696 +0x12b
k8s.io/klog.(*loggingT).print(...)
	/go/src/github.com/onosproject/onos-topo/vendor/k8s.io/klog/klog.go:687
k8s.io/klog.Fatal(...)
	/go/src/github.com/onosproject/onos-topo/vendor/k8s.io/klog/klog.go:1236
main.main()
	/go/src/github.com/onosproject/onos-topo/cmd/onos-topo/onos-topo.go:78 +0x4ca
scondon@Z420:~/go/src/github.com/onosproject/onos-test$
```

**Comment by SeanCondon** [comment]
Just FYI - the corresponding logs for raft and atomix are
```
scondon@Z420:~/go/src/github.com/onosproject/onos-test$ kubectl logs raft-1-0 -n sean-1
2019/08/16 09:13:00 proto: duplicate proto type registered: atomix.service.TestValueSnapshot
2019/08/16 09:13:00 proto: duplicate proto type registered: atomix.service.SetRequest
2019/08/16 09:13:00 proto: duplicate proto type registered: atomix.service.SetResponse
2019/08/16 09:13:00 proto: duplicate proto type registered: atomix.service.GetRequest
2019/08/16 09:13:00 proto: duplicate proto type registered: atomix.service.GetResponse
Aug 16 09:13:00.251 INFO              Starting protocol
Aug 16 09:13:00.251 INFO   raft-1-0   Server is running
Aug 16 09:13:00.251 INFO   raft-1-0   Transitioning to Follower
Aug 16 09:13:00.251 DEBUG  raft-1-0   Single node cluster; starting election
Aug 16 09:13:00.251 INFO   raft-1-0   Transitioning to Candidate
Aug 16 09:13:00.251 DEBUG  raft-1-0   Single node cluster; skipping election
Aug 16 09:13:00.251 INFO   raft-1-0   Transitioning to Leader
Aug 16 09:13:00.251 INFO   raft-1-0   Server is ready
Aug 16 09:13:00.251 INFO              Listening on port 5678
Aug 16 09:13:00.251 TRACE  raft-1-0   Applying 1
Aug 16 09:13:00.251 INFO              Starting gRPC server
scondon@Z420:~/go/src/github.com/onosproject/onos-test$ kubectl logs atomix-controller-7cdbc4d7f5-rm2b6 -n sean-1
{"level":"info","ts":1565946762.995069,"logger":"cmd","msg":"Go Version: go1.12.6"}
{"level":"info","ts":1565946762.9951062,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1565946762.9953969,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1565946763.035381,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1565946763.0386553,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1565946763.072183,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1565946763.0725496,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"partition-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1565946763.0728106,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"partition-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1565946763.0730345,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"partitionset-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1565946763.0732386,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"partitionset-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1565946763.073295,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1565946763.1737597,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"partitionset-controller"}
{"level":"info","ts":1565946763.1737597,"logger":"controller_atomix","msg":"Starting controller server"}
{"level":"info","ts":1565946763.1738002,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"partition-controller"}
{"level":"info","ts":1565946763.2741337,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"partitionset-controller","worker count":1}
{"level":"info","ts":1565946763.274246,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"partition-controller","worker count":1}
{"level":"info","ts":1565946766.7182229,"logger":"controller_partitiongroup","msg":"Reconciling PartitionSet","Request.Namespace":"sean-1","Request.Name":"raft"}
{"level":"info","ts":1565946766.8187501,"logger":"controller_partitiongroup","msg":"Creating service","Name":"raft","Namespace":"sean-1"}
{"level":"info","ts":1565946766.9264836,"logger":"controller_partitiongroup","msg":"Creating endpoints","Name":"raft","Namespace":"sean-1"}
{"level":"info","ts":1565946766.9347956,"logger":"controller_partitiongroup","msg":"Creating partition","Name":"raft-1","Namespace":"sean-1"}
{"level":"info","ts":1565946766.939796,"logger":"controller_partitiongroup","msg":"Reconciling PartitionSet","Request.Namespace":"sean-1","Request.Name":"raft"}
{"level":"info","ts":1565946766.939812,"logger":"controller_partition","msg":"Reconciling Partition","Request.Namespace":"sean-1","Request.Name":"raft-1"}
{"level":"info","ts":1565946767.040249,"logger":"controller_partition","msg":"Creating node ConfigMap","Name":"raft-1","Namespace":"sean-1"}
{"level":"info","ts":1565946767.1448221,"logger":"controller_partition","msg":"Creating pod disruption budget","Name":"raft-1","Namespace":"sean-1"}
{"level":"info","ts":1565946767.1516943,"logger":"controller_partition","msg":"Creating partition set","Name":"raft-1","Namespace":"sean-1"}
{"level":"info","ts":1565946767.1703029,"logger":"controller_partition","msg":"Creating partition service","Name":"raft-1","Namespace":"sean-1"}
{"level":"info","ts":1565946767.185291,"logger":"controller_partition","msg":"Creating headless partition service","Name":"raft-1","Namespace":"sean-1"}
{"level":"info","ts":1565946767.187503,"logger":"controller_partition","msg":"Creating endpoint","Name":"raft-1","Namespace":"sean-1"}
{"level":"info","ts":1565946767.1875663,"logger":"controller_partition","msg":"Updating endpoint addresses to ready","Name":"raft-1","Namespace":"sean-1"}
{"level":"info","ts":1565946767.1909344,"logger":"controller_partition","msg":"Reconciling Partition","Request.Namespace":"sean-1","Request.Name":"raft-1"}
{"level":"info","ts":1565946767.1910658,"logger":"controller_partition","msg":"Creating endpoint","Name":"raft-1","Namespace":"sean-1"}
{"level":"info","ts":1565946787.3310015,"logger":"controller_partition","msg":"Reconciling Partition","Request.Namespace":"sean-1","Request.Name":"raft-1"}
{"level":"info","ts":1565946787.3311274,"logger":"controller_partition","msg":"Creating endpoint","Name":"raft-1","Namespace":"sean-1"}
{"level":"info","ts":1565946787.331159,"logger":"controller_partition","msg":"Updating partition status","Name":"raft-1","Namespace":"sean-1"}
{"level":"info","ts":1565946787.3343103,"logger":"controller_partitiongroup","msg":"Reconciling PartitionSet","Request.Namespace":"sean-1","Request.Name":"raft"}
{"level":"info","ts":1565946787.334383,"logger":"controller_partitiongroup","msg":"Updating partition set status","Name":"raft","Namespace":"sean-1"}
{"level":"info","ts":1565946787.3343115,"logger":"controller_partition","msg":"Reconciling Partition","Request.Namespace":"sean-1","Request.Name":"raft-1"}
{"level":"info","ts":1565946787.3344781,"logger":"controller_partition","msg":"Creating endpoint","Name":"raft-1","Namespace":"sean-1"}
{"level":"info","ts":1565946787.3387663,"logger":"controller_partitiongroup","msg":"Reconciling PartitionSet","Request.Namespace":"sean-1","Request.Name":"raft"}
```

**Comment by SeanCondon** [comment]
It's a known configuration problem with Microk8s
See "My pods can’t reach the internet or each other (but my MicroK8s host machine can)…" in
https://microk8s.io/docs/
